# Funding configuration for the Akasha project

github: []
patreon: []
open_collective: []
ko_fi: []
tidelift: []
community_bridge: []
liberapay: []
issuehunt: []
otechie: []

custom:
  - "https://buymeacoffee.com/Thegreatoleander"
  - "https://etherscan.io/address/0x185325DB018e6ECBb92Bf0443ABFBbB3a07cE713"
